FROM alpine:3.7
MAINTAINER shiuday@gmail.com

RUN apk upgrade --update && apk --no-cache add \
            curl \
            vim \
            bash \
            git \
            wget \
            supervisor \
            nginx

